<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <EnableMicrosoftTestingPlatformRunner>true</EnableMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Respawn" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="Verify.TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\apps\backend\DotnetVue3TemplateRu.Api\DotnetVue3TemplateRu.Api.csproj" />
  </ItemGroup>

</Project>
